apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Nome do serviço do prometheus no docker-compose
    isDefault: true
    editable: false
